# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
darkmode: false

# Personal info
name: Aleksey Rybalkin
title: Software Developer Engineer in Test
email: rybalkine@gmail.com
website: www.github.com/rybalkin-an

# Social links
# twitter_username: facespics
github_username:  rybalkin-an
# dribbble_username: jekyll
facebook_username: alexei.rybalkine
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: aleksei-rybalkin-b366a9167
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/11b36b21-2f66-4d47-9dc6-b9a886f42ada.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Aleksey and I'm a SDET.  
  My Tech stack is:
   - Java, Maven, TestNG, Selenide, REST-assured, JDBC, Allure, Selenoid, Intellij IDEA
   - Python, Pytest, Selenium WebDriver, Pycharm
   - SQL, DBeaver 
   - Chrome DevTools, Postman
   - Docker, Jenkins

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
# Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
