# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
darkmode: false

# Personal info
name: Aleksey Rybalkin
title: Software Developer Engineer in Test
email: rybalkine@gmail.com
# website: www.github.com/rybalkin-an

# Social links
# twitter_username: facespics
github_username:  rybalkin-an
# dribbble_username: jekyll
facebook_username: alexei.rybalkine
# flickr_username: jekyll
instagram_username: leshjkestreetarthunter
linkedin_username: aleksey-rybalkin
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/4785e26b-af26-444e-afd4-24caf8cea6a21.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Aleksey, I'm a SDET from [Samara](https://goo.gl/maps/t46pgar74FkLE43BA), Russia  
  
  My Tech stack is:
   - Java, Maven, Gradle, TestNG, JUnit 5, Selenide, REST-assured, JDBC, Allure, Selenoid, Intellij IDEA
   - Python, Pytest, Selenium WebDriver, Pycharm
   - SQL, DBeaver 
   - Chrome DevTools, Postman, SoapUI
   - Docker, Jenkins, Teamcity, Kotlin DSL
   
   Ich kann ein bisschen Deutsch sprechen (Goethe-Zertifikat B1)

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
# Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
